AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: SAM Local
Resources:
  createmap:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Runtime: nodejs14.x
      Handler: handler.lambda_handler
      Timeout: 600